// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Directive: videoCamera', function() {
    var element;
    beforeEach(module('videoCaptureApp'));
    element = {};
    return it('should make hidden element visible', inject(function($rootScope, $compile) {
      element = angular.element('<video-camera></video-camera>');
      element = $compile(element)($rootScope);
      return expect(element.text()).toBe('this is the videoCamera directive');
    }));
  });

}).call(this);
