// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('videoCaptureApp', []).config(function($routeProvider, $locationProvider) {
    var gifResolve;
    gifResolve = function(Aws) {
      return Aws.getGifs();
    };
    $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl',
      resolve: {
        gifs: ['Aws', gifResolve]
      }
    }).when('/display', {
      templateUrl: 'views/display.html',
      controller: 'DisplayCtrl',
      resolve: {
        gifs: ['Aws', gifResolve]
      }
    }).otherwise({
      redirectTo: '/'
    });
    return $locationProvider.html5Mode(true);
  }).run(function($rootScope) {
    return $rootScope.MAX_NUM_GIFS = 50;
  });

}).call(this);
